# Site
repository: jikime/jikime.github.io
# favicon: images/favicon.ico

# Personal info
name: 김동학
title: TypeScript/React & Golang/PHP Full Stack 개발자
email: jikime@gmail.com
# website: https://jiki.me

# Social links
github_username:  jikime
# facebook_username: jikime

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  대학교때 취미로 시작했던 학과 홈페이지 만들기를 시작으로 웹디자인, 서버관리, 백엔드, 프론트엔드 개발을 거쳐 현재 <mark>Full Stack 개발자</mark>의 길을 걷고 있습니다. <br />
  주어진 환경에서 최적의 기술을 찾고 <mark>빠르게 필요한 기술을 습득/연구</mark>하여 프로젝트를 리딩하는 장점이 있습니다. <br />
  최근에는 컨테이너기반 <mark>MSA(Microservice Architecture)</mark>을 구현하고 배포하는 일과 <mark>개발 리더</mark>로서 <mark>프로젝트 코어 구현, 설계 및 교육</mark>등을 주요 업무로 하고 있습니다. <br /><br />
  처음 개발을 하면서 느꼇던 설레임, 기대감에 열정을 더해서 오늘도 회사와 팀에 도움이 되고자 구글링중입니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  오래전 일이지만 일반인을 대상으로 강의를 하였습니다.
   - 서울 중앙정보처리학원(1개월 과정) : PHP
   - 청주 YWCA(1개월 과정) : 홈페이지 만들기
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
